$(document).ready(function(){
  $(".onclick").click(function(){
    $(".design-hidden").toggle();
    $(".design-showing").toggle();
  });
  $(".click").click(function(){
    $(".dev-hidden").toggle();
    $(".Dev-showing").toggle();
  });
  $(".clik").click(function(){
    $(".product-hidden").toggle();
    $(".prod-showing").toggle();
  });
});
